version: '3.8'

services:
  api-gateway:
    #container_name: currency-exchange-service   
    build:
      context: ./Docker-api-gateway 
    image: api-gateway:1.0.0
    ports:
      - "8765:8765"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on: 
      - naming-server
      - currency-exchange-service
      - currency-conversion-service
      - zipkin-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka    
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/     
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit    
    networks:
      - currency-network 

  currency-conversion-service:
    #container_name: currency-exchange-service   
    build:
      context: ./Docker-currency-conversion-service  
    image: currency-conversion-service:1.0.0
    ports:
      - "8100:8100"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on: 
      - naming-server
      - currency-exchange-service
      - zipkin-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka    
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/     
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit 
    networks:
      - currency-network 
      
  currency-exchange-service:
    #container_name: currency-exchange-service   
    build:
      context: ./Docker-currency-exchange-service  
    image: currency-exchange-service:1.0.0
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on: 
      - naming-server
      - zipkin-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/     
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit     
    networks:
      - currency-network 

  naming-server:  
    #container_name: naming-server
    build:
      context: ./Docker-naming-server
    image: naming-server:1.0.0
    ports:
      - "8761:8761" 
    deploy:
      resources:
        limits:
          memory: 700m  
    networks:
      - currency-network 

  zipkin-server:
    image: openzipkin/zipkin:2.23
    deploy:
      resources:
        limits:
          memory: 300m  
    ports:
      - "9411:9411"
    depends_on: 
      - rabbitmq
    restart: always #Restart if there is a problem starting up
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    networks:
      - currency-network  

  rabbitmq:
    image: rabbitmq:3.8.12-management
    deploy:
      resources:
        limits:
          memory: 300m  
    ports:
      - "5672:5672"
      - "15672:15672"#managment port
    networks:
      - currency-network    
            
networks:
  currency-network: